### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by EilrahcF** [MusicTheorist/ArrayVisualizer#12]
It seems that the particular algorithm "Timesort" has a few issues around it.
1: Setting timesorts multiplier to "Infinity" Crashes the program.
2: Setting the multiplier to "-Infinity" only seems to work on half the array before resorting to insertion sort. How ever once the algorithm is done, some of the elements have shrunk in size, making them the same value as some others (Try sorting low ammounts of numbers with this, such as 8 - 64 to see this at full effect).
3: Setting timesorts multiplier to any negetive integer makes the algorithm fail, though I belive this may be intentional.

**Comment by MusicTheorist** [comment]
Fixed.

threads/RunDistributionSort.java:139
`if(sort.getReportSortID().equals("Timesort")) {
                        try {
                            bucketCount = (int) Math.ceil(Double.parseDouble(JEnhancedOptionPane.showInputDialog("Enter delay per number in milliseconds:", new Object[]{"Enter", "Use default"})));
                        }
                        catch(Exception e) {
                            bucketCount = 10;
                        }
                    }
`
changed to
`if(sort.getReportSortID().equals("Timesort")) {
                        try {
                            bucketCount = Math.abs(Integer.parseInt(JEnhancedOptionPane.showInputDialog("Enter delay per number in milliseconds:", new Object[]{"Enter", "Use default"})));
                        }
                        catch(Exception e) {
                            bucketCount = 10;
                        }
                    }
`

This fix will be released with the program's next update. Thanks for the bug report!
