### ISSUE TITLE
Optimized Bubblesort causing issues

### ISSUE THREAD

**Issue by EilrahcF** [MusicTheorist/ArrayVisualizer#13]
When I press the skip button with large ammounts of numbers with optimized bubblesort, the program freezes, becomes unresponsive, makes weird buggy noises and shows no visualisation untill the algorithm is finished in the background, in which everything returns to normal. I belive this may happen with other algorithms too, but im not too sure since I tested normal bubblesort and optimized cocktail shaker sort and nothing odd happened during those tests.

**Comment by EilrahcF** [comment]
High numbers such as 16k normally

**Comment by EilrahcF** [comment]
But sometimes 8k

**Comment by MusicTheorist** [comment]
Okay, I was able to reproduce when I turned off both the shuffle and green sweep animation.

**Comment by MusicTheorist** [comment]
Okay, I've figured out why this bug is happening. It's a consequence of w0rthy's old visual code. This will be automatically fixed in the future when I finished rewriting the visual code.

**Comment by MusicTheorist** [comment]
I was able to find a patch for now! Consider this issue fixed in the next update.
