### ISSUE TITLE
Add custom array size dialog between 2 and 16,384 integers (can be non-power-of-two)

### ISSUE THREAD

**Issue by MusicTheorist** [MusicTheorist/ArrayVisualizer#30]
Ensure all sort implementations can handle both power-of-two and non-power-of-two array lengths.

**Comment by fundamentals-fontdevelopment** [comment]
Just update to this: https://github.com/MusicTheorist/ArrayVisualizer/pull/71 . Select any integer from 1 to 4096 on a single slider.

**Comment by MusicTheorist** [comment]
That design has the glaring issue of not being able to see all those numbers. I think what I'm leaning towards is giving the user a text box to enter in a custom length instead.

**Comment by MusicTheorist** [comment]
Available in the next update!

**Comment by rylid-umil** [comment]
now i cant get any number thats the power of 2 larger than 64 and thats not 2,048 or 32 thousand
