### ISSUE TITLE
Reads.compare() method with delay and mark arguments

### ISSUE THREAD

**Issue by MusicTheorist** [MusicTheorist/ArrayVisualizer#55]

**Comment by MusicTheorist** [comment]
Will be available next update.

**Comment by fundamentals-fontdevelopment** [comment]
And the WAV sound engine directly injects the sound code into the comparison, ensuring each comparison plays a sound once.

**Comment by MusicTheorist** [comment]
@fundamentals-fontdevelopment I am no longer interested in your WAV sound engine.
