### ISSUE TITLE
A better picture for custom visual

### ISSUE THREAD

**Issue by fundamentals-fontdevelopment** [MusicTheorist/ArrayVisualizer#75]
I think this would be a better picture to use for the custom visual:

![](https://i.imgur.com/KWflzxO.png)

**Comment by MusicTheorist** [comment]
Uhh... What is this?

**Comment by fundamentals-fontdevelopment** [comment]
I have no more use for sorting but this is the best image for your Array Visualizer.

**Comment by MusicTheorist** [comment]
Are you trying to troll me?

**Comment by EilrahcF** [comment]
_Geuss you wanted to go out with a bang huh_
